#!/bin/bash
# vector sigma 2018

export LC_ALL=C

bold=$(tput bold)
normal=$(tput sgr0)

quiet="-quiet"
arch=""
force64BitOnly=1
UseModernBuildSystem=""

SRCROOT="$(dirname $0)"
cd "${SRCROOT}"
PREFERRED_SDK="macosx10.11" # Default sdk to build kexts. If exist
PREFERRED_CONF='Release 10.6' # Default configuration to build kexts.
PREFERRED_CONF_APPS='Release' # Default configuration to build kexts.

VERSION=$(svn info | grep '^Revision:' | tr -cd [:digit:])

checkDefaultSDK() {
if [[ -z "$(xcodebuild -showsdks | grep $PREFERRED_SDK)" ]]; then
  PREFERRED_SDK=macosx
  echo "   ..using the latest available sdk"
else
  echo "   ..using the sdk: $PREFERRED_SDK"
fi
}

# HWMonitorSMC.app v2 can be compiled only with Xcode 9.4.1 + and swift 4.2
buildv2=0
xver=$(/usr/bin/xcodebuild -version | grep 'Xcode' | awk '{print $NF}')
case "$xver" in
    1*)
        UseModernBuildSystem='-UseModernBuildSystem=0'
        buildv2=1
    ;;
    9.4.1)
        buildv2=1
    ;;
    *)
        quiet=""
        buildv2=0
    ;;
esac

if [[ $force64BitOnly -eq 1 ]]; then
  arch='ARCHS=x86_64 VALID_ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES'
fi

rm -rf compilations/Extensions
rm -rf compilations/HWMonitorSMC
rm -rf compilations/HWMonitorSMC2

mkdir -p compilations/Extensions
mkdir -p compilations/HWMonitorSMC
mkdir -p compilations/HWMonitorSMC2
mkdir -p compilations/Extensions_SYMROOT
mkdir -p compilations/HWMonitorSMC_SYMROOT
mkdir -p compilations/HWMonitorSMC2_SYMROOT

cd trunk

if [[ -d ../kexts_prebuilt ]]; then
  # building kernel extensions
  echo "${bold}** Using HWSensor's pre built extensions **${normal}"
  cp -R ../kexts_prebuilt/*.kext "${SRCROOT}/compilations/Extensions/"

else
  # building kernel extensions
  echo "${bold}** Building HWSensor's extensions r${VERSION} **${normal}"
  checkDefaultSDK
  xcodebuild  $arch $quiet \
              -project HWSensors.xcodeproj \
              -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu` \
              -sdk $PREFERRED_SDK \
              -configuration "${PREFERRED_CONF}" \
              ALWAYS_SEARCH_USER_PATHS=0 $UseModernBuildSystem \
              SYMROOT="${SRCROOT}/compilations/Extensions_SYMROOT" || exit 1

  cp -R "${SRCROOT}/compilations/Extensions_SYMROOT/${PREFERRED_CONF}"/*.kext \
                                          "${SRCROOT}/compilations/Extensions/"
fi

echo
for i in "${SRCROOT}/compilations/Extensions"/* ; do
  if [[ -d "$i" ]]; then
    kext_ver=$(defaults read "${i}"/Contents/Info CFBundleVersion)
    echo $(basename "$i") "(${kext_ver})"
  fi
done
echo
if [[ -n $1 ]]; then
  open "${SRCROOT}/compilations/Extensions"
  exit 0
fi

# building HWMonitorSMC.app v1.x
echo "${bold}** Building HWMonitorSMC.app v1 **${normal}"
cd  "${SRCROOT}/trunk/hwmonitor"
xcodebuild $arch $quiet -project HWMonitorSMC.xcodeproj \
                -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu` \
                -sdk macosx \
                -configuration "${PREFERRED_CONF_APPS}" \
                SYMROOT="${SRCROOT}/compilations/HWMonitorSMC_SYMROOT" || exit 1

cp -R "${SRCROOT}/compilations/HWMonitorSMC_SYMROOT/${PREFERRED_CONF_APPS}"/HWMonitorSMC.app \
                                              "${SRCROOT}/compilations/HWMonitorSMC/"


if [ "$buildv2" -eq "1" ]; then
  if [[ ! -d "/Library/Frameworks/IntelPowerGadget.framework" ]]; then
    printf "\033[0;31mHWMonitorSMC2 require the IntelPowerGadget.framework to be installed,\n"
    printf "download here:\033[0m https://software.intel.com/en-us/articles/intel-power-gadget-20\n\n"
    sleep 2
    exit 0
  fi
  echo "${bold}** Building HWMonitorSMC.app v2 **${normal}"
  cd  "${SRCROOT}/trunk/hwmonitor2"
  xcodebuild $arch $quiet -project HWMonitorSMC.xcodeproj \
                    -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu` \
                    -sdk macosx \
                    -configuration "${PREFERRED_CONF_APPS}" \
                    SYMROOT="${SRCROOT}/compilations/HWMonitorSMC2_SYMROOT" || exit 1
  cp -R "${SRCROOT}/compilations/HWMonitorSMC2_SYMROOT/${PREFERRED_CONF_APPS}"/HWMonitorSMC2.app \
                                                          "${SRCROOT}/compilations/HWMonitorSMC2/"
else
  echo "HWMonitorSMC.app v2.x requires Xcode 9.4.1 +"
fi

exit 0
